[package]
name = "dawr"
version = "0.0.2"
authors = ["Taylor Hornby <taylor@defuse.ca>"]
license = "MIT"
repository = "https://github.com/defuse/DAWr"
description = "A DAW-like audio playground for Rust coders."

[dependencies]
portaudio = "0.7"
rand = "0.4"
hound = "3.4"
